version: '3.3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    ports:
      - "5443:5432"